Initial commit
Zawadidone/timesketch pull request #1
Opened 2023-01-26 14:06 UTC by rickvandreunen

2023-01-26 14:11 UTC, Zawadidone commented on timesketch/api/v1/resources/timeline.py
> +        # FIXME
Is this variable needed for the feature this PR implements?

Does this break the usage of this PR without a timeline ID?

2023-01-26 14:18 UTC, Zawadidone requested changes
Can additionally a test function be added to `end_to_end_tests/client_test.py` that does what your test script executes with two timelines? With additional checks to verify if two seperate timelines are added with the right data.

2023-01-26 14:18 UTC, Zawadidone commented on timesketch/api/v1/resources/event.py
> +                    # "bool": {
Is it possible to combine a term and a bool query? https://stackoverflow.com/questions/54896395/how-to-compound-terms-query-and-bool-query-together-in-elasticsearch

2023-01-26 14:18 UTC, Zawadidone commented on timesketch/api/v1/resources/event.py
> +        if timeline_filter_id:
Add comment about usage of `timeline_id` means that the documents are filtered, etc

2023-01-26 14:18 UTC, Zawadidone commented on timesketch/api/v1/resources/event.py
> +
?

2023-01-26 14:18 UTC, Zawadidone commented on api_client/python/timesketch_api_client/sketch.py
> -
?

2023-01-26 14:18 UTC, Zawadidone commented on api_client/python/timesketch_api_client/sketch.py
> +
?

2023-01-26 14:18 UTC, Zawadidone commented on api_client/python/timesketch_api_client/sketch.py
> +        # This prevents adding of data into existing timeline thus it is commenten out for
Add comment above code

2023-01-26 14:18 UTC, Zawadidone commented on api_client/python/timesketch_api_client/sketch.py
> +            timeline_filter_id: optional string to filter on documents in an
```suggestion
            timeline_filter_id: optional integer to filter on documents in an
```

2023-02-01 12:19 UTC, rickvandreunen commented on timesketch/api/v1/resources/timeline.py
> +        # FIXME
WIthout this set to false an error that the sketch ID dis not match with the timeline sketch ID is thrown and only the first timeline in a sketch is created. 

Example:
`python test_direct_ingestion.py
Sketch id: 12 with uuid: dcd61e0a-e1eb-47b5-8b6b-e9a18252ee10 has been created
Timeline: #0 dcd61e0a-e1eb-47b5-8b6b-e9a18252ee10 has been created
Traceback (most recent call last):
  File "C:\Projects\timesketch\api_client\python\test_direct_ingestion.py", line 55, in <module>
    ingest()  # ingest data into Timesketch
    ^^^^^^^^
  File "C:\Projects\timesketch\api_client\python\test_direct_ingestion.py", line 40, in ingest
    sketch.generate_timeline_from_es_index(
  File "C:\Projects\timesketch\api_client\python\timesketch_api_client\sketch.py", line 1814, in generate_timeline_from_es_index
    error.error_message(
  File "C:\Projects\timesketch\api_client\python\timesketch_api_client\error.py", line 109, in error_message
    raise error(
ValueError: Unable to add timeline identifier to data, with error [404] NOT FOUND The sketch ID (12) does not match with the timeline sketch ID (5)`

2023-02-01 12:39 UTC, Zawadidone requested changes

2023-02-01 12:39 UTC, Zawadidone commented on api_client/python/timesketch_api_client/sketch.py
> +        if not timeline_filter_id:
```suggestion
        if timeline_filter_id is None:
```

2023-02-01 12:39 UTC, Zawadidone commented on api_client/python/timesketch_api_client/sketch.py
> +            timeline_filter_id: optional integer to filter on documents in an
Sorry my bad this should be a string

```suggestion
            timeline_filter_id: optional string to filter on documents in an
```

2023-02-01 12:39 UTC, Zawadidone commented on api_client/python/timesketch_api_client/sketch.py
> +        # since otherwise no more than 1 timeline can be created
```suggestion
        # If a timeline identifier is used this step is skipped
        # otherwise no more than one timeline can be created from an index
```

2023-02-02 13:22 UTC, rickvandreunen commented on api_client/python/timesketch_api_client/sketch.py
>              index_name: optional string for the SearchIndex name, defaults
Issue will be picked up either this weekend or next week

2023-02-03 19:33 UTC, Zawadidone requested changes

2023-02-03 20:02 UTC, Zawadidone approved these changes
Later changes can be applied in the Timesketch hnhdev repository

2023-02-03 20:02 UTC, merged